// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/messages/indoor_climate.proto

package com.vladzasoba.protobuf;

public final class ClimateProtos {
  private ClimateProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ValueTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.ValueType)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string unit = 1;</code>
     */
    boolean hasUnit();
    /**
     * <code>required string unit = 1;</code>
     */
    java.lang.String getUnit();
    /**
     * <code>required string unit = 1;</code>
     */
    com.google.protobuf.ByteString
        getUnitBytes();

    /**
     * <code>required fixed64 value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>required fixed64 value = 2;</code>
     */
    long getValue();
  }
  /**
   * Protobuf type {@code protobuf.ValueType}
   */
  public  static final class ValueType extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.ValueType)
      ValueTypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ValueType.newBuilder() to construct.
    private ValueType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ValueType() {
      unit_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ValueType();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ValueType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              unit_ = bs;
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              value_ = input.readFixed64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vladzasoba.protobuf.ClimateProtos.internal_static_protobuf_ValueType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vladzasoba.protobuf.ClimateProtos.internal_static_protobuf_ValueType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.vladzasoba.protobuf.ClimateProtos.ValueType.class, com.vladzasoba.protobuf.ClimateProtos.ValueType.Builder.class);
    }

    private int bitField0_;
    public static final int UNIT_FIELD_NUMBER = 1;
    private volatile java.lang.Object unit_;
    /**
     * <code>required string unit = 1;</code>
     */
    public boolean hasUnit() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string unit = 1;</code>
     */
    public java.lang.String getUnit() {
      java.lang.Object ref = unit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          unit_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string unit = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUnitBytes() {
      java.lang.Object ref = unit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private long value_;
    /**
     * <code>required fixed64 value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required fixed64 value = 2;</code>
     */
    public long getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUnit()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, unit_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeFixed64(2, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, unit_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.vladzasoba.protobuf.ClimateProtos.ValueType)) {
        return super.equals(obj);
      }
      com.vladzasoba.protobuf.ClimateProtos.ValueType other = (com.vladzasoba.protobuf.ClimateProtos.ValueType) obj;

      if (hasUnit() != other.hasUnit()) return false;
      if (hasUnit()) {
        if (!getUnit()
            .equals(other.getUnit())) return false;
      }
      if (hasValue() != other.hasValue()) return false;
      if (hasValue()) {
        if (getValue()
            != other.getValue()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUnit()) {
        hash = (37 * hash) + UNIT_FIELD_NUMBER;
        hash = (53 * hash) + getUnit().hashCode();
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getValue());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.vladzasoba.protobuf.ClimateProtos.ValueType parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vladzasoba.protobuf.ClimateProtos.ValueType parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vladzasoba.protobuf.ClimateProtos.ValueType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vladzasoba.protobuf.ClimateProtos.ValueType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vladzasoba.protobuf.ClimateProtos.ValueType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vladzasoba.protobuf.ClimateProtos.ValueType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vladzasoba.protobuf.ClimateProtos.ValueType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.vladzasoba.protobuf.ClimateProtos.ValueType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.vladzasoba.protobuf.ClimateProtos.ValueType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.vladzasoba.protobuf.ClimateProtos.ValueType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.vladzasoba.protobuf.ClimateProtos.ValueType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.vladzasoba.protobuf.ClimateProtos.ValueType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.vladzasoba.protobuf.ClimateProtos.ValueType prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.ValueType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.ValueType)
        com.vladzasoba.protobuf.ClimateProtos.ValueTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.vladzasoba.protobuf.ClimateProtos.internal_static_protobuf_ValueType_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.vladzasoba.protobuf.ClimateProtos.internal_static_protobuf_ValueType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.vladzasoba.protobuf.ClimateProtos.ValueType.class, com.vladzasoba.protobuf.ClimateProtos.ValueType.Builder.class);
      }

      // Construct using com.vladzasoba.protobuf.ClimateProtos.ValueType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        unit_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.vladzasoba.protobuf.ClimateProtos.internal_static_protobuf_ValueType_descriptor;
      }

      @java.lang.Override
      public com.vladzasoba.protobuf.ClimateProtos.ValueType getDefaultInstanceForType() {
        return com.vladzasoba.protobuf.ClimateProtos.ValueType.getDefaultInstance();
      }

      @java.lang.Override
      public com.vladzasoba.protobuf.ClimateProtos.ValueType build() {
        com.vladzasoba.protobuf.ClimateProtos.ValueType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.vladzasoba.protobuf.ClimateProtos.ValueType buildPartial() {
        com.vladzasoba.protobuf.ClimateProtos.ValueType result = new com.vladzasoba.protobuf.ClimateProtos.ValueType(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.unit_ = unit_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.value_ = value_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.vladzasoba.protobuf.ClimateProtos.ValueType) {
          return mergeFrom((com.vladzasoba.protobuf.ClimateProtos.ValueType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.vladzasoba.protobuf.ClimateProtos.ValueType other) {
        if (other == com.vladzasoba.protobuf.ClimateProtos.ValueType.getDefaultInstance()) return this;
        if (other.hasUnit()) {
          bitField0_ |= 0x00000001;
          unit_ = other.unit_;
          onChanged();
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasUnit()) {
          return false;
        }
        if (!hasValue()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.vladzasoba.protobuf.ClimateProtos.ValueType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.vladzasoba.protobuf.ClimateProtos.ValueType) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object unit_ = "";
      /**
       * <code>required string unit = 1;</code>
       */
      public boolean hasUnit() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string unit = 1;</code>
       */
      public java.lang.String getUnit() {
        java.lang.Object ref = unit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            unit_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string unit = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUnitBytes() {
        java.lang.Object ref = unit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          unit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string unit = 1;</code>
       */
      public Builder setUnit(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        unit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string unit = 1;</code>
       */
      public Builder clearUnit() {
        bitField0_ = (bitField0_ & ~0x00000001);
        unit_ = getDefaultInstance().getUnit();
        onChanged();
        return this;
      }
      /**
       * <code>required string unit = 1;</code>
       */
      public Builder setUnitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        unit_ = value;
        onChanged();
        return this;
      }

      private long value_ ;
      /**
       * <code>required fixed64 value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required fixed64 value = 2;</code>
       */
      public long getValue() {
        return value_;
      }
      /**
       * <code>required fixed64 value = 2;</code>
       */
      public Builder setValue(long value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.ValueType)
    }

    // @@protoc_insertion_point(class_scope:protobuf.ValueType)
    private static final com.vladzasoba.protobuf.ClimateProtos.ValueType DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.vladzasoba.protobuf.ClimateProtos.ValueType();
    }

    public static com.vladzasoba.protobuf.ClimateProtos.ValueType getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ValueType>
        PARSER = new com.google.protobuf.AbstractParser<ValueType>() {
      @java.lang.Override
      public ValueType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ValueType(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ValueType> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ValueType> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.vladzasoba.protobuf.ClimateProtos.ValueType getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface IndoorClimateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.IndoorClimate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .protobuf.ValueType temperature = 1;</code>
     */
    boolean hasTemperature();
    /**
     * <code>required .protobuf.ValueType temperature = 1;</code>
     */
    com.vladzasoba.protobuf.ClimateProtos.ValueType getTemperature();
    /**
     * <code>required .protobuf.ValueType temperature = 1;</code>
     */
    com.vladzasoba.protobuf.ClimateProtos.ValueTypeOrBuilder getTemperatureOrBuilder();
  }
  /**
   * Protobuf type {@code protobuf.IndoorClimate}
   */
  public  static final class IndoorClimate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.IndoorClimate)
      IndoorClimateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IndoorClimate.newBuilder() to construct.
    private IndoorClimate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IndoorClimate() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IndoorClimate();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IndoorClimate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.vladzasoba.protobuf.ClimateProtos.ValueType.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = temperature_.toBuilder();
              }
              temperature_ = input.readMessage(com.vladzasoba.protobuf.ClimateProtos.ValueType.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(temperature_);
                temperature_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vladzasoba.protobuf.ClimateProtos.internal_static_protobuf_IndoorClimate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vladzasoba.protobuf.ClimateProtos.internal_static_protobuf_IndoorClimate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.vladzasoba.protobuf.ClimateProtos.IndoorClimate.class, com.vladzasoba.protobuf.ClimateProtos.IndoorClimate.Builder.class);
    }

    private int bitField0_;
    public static final int TEMPERATURE_FIELD_NUMBER = 1;
    private com.vladzasoba.protobuf.ClimateProtos.ValueType temperature_;
    /**
     * <code>required .protobuf.ValueType temperature = 1;</code>
     */
    public boolean hasTemperature() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .protobuf.ValueType temperature = 1;</code>
     */
    public com.vladzasoba.protobuf.ClimateProtos.ValueType getTemperature() {
      return temperature_ == null ? com.vladzasoba.protobuf.ClimateProtos.ValueType.getDefaultInstance() : temperature_;
    }
    /**
     * <code>required .protobuf.ValueType temperature = 1;</code>
     */
    public com.vladzasoba.protobuf.ClimateProtos.ValueTypeOrBuilder getTemperatureOrBuilder() {
      return temperature_ == null ? com.vladzasoba.protobuf.ClimateProtos.ValueType.getDefaultInstance() : temperature_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTemperature()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getTemperature().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getTemperature());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTemperature());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.vladzasoba.protobuf.ClimateProtos.IndoorClimate)) {
        return super.equals(obj);
      }
      com.vladzasoba.protobuf.ClimateProtos.IndoorClimate other = (com.vladzasoba.protobuf.ClimateProtos.IndoorClimate) obj;

      if (hasTemperature() != other.hasTemperature()) return false;
      if (hasTemperature()) {
        if (!getTemperature()
            .equals(other.getTemperature())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTemperature()) {
        hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
        hash = (53 * hash) + getTemperature().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.vladzasoba.protobuf.ClimateProtos.IndoorClimate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vladzasoba.protobuf.ClimateProtos.IndoorClimate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vladzasoba.protobuf.ClimateProtos.IndoorClimate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vladzasoba.protobuf.ClimateProtos.IndoorClimate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vladzasoba.protobuf.ClimateProtos.IndoorClimate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vladzasoba.protobuf.ClimateProtos.IndoorClimate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vladzasoba.protobuf.ClimateProtos.IndoorClimate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.vladzasoba.protobuf.ClimateProtos.IndoorClimate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.vladzasoba.protobuf.ClimateProtos.IndoorClimate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.vladzasoba.protobuf.ClimateProtos.IndoorClimate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.vladzasoba.protobuf.ClimateProtos.IndoorClimate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.vladzasoba.protobuf.ClimateProtos.IndoorClimate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.vladzasoba.protobuf.ClimateProtos.IndoorClimate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.IndoorClimate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.IndoorClimate)
        com.vladzasoba.protobuf.ClimateProtos.IndoorClimateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.vladzasoba.protobuf.ClimateProtos.internal_static_protobuf_IndoorClimate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.vladzasoba.protobuf.ClimateProtos.internal_static_protobuf_IndoorClimate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.vladzasoba.protobuf.ClimateProtos.IndoorClimate.class, com.vladzasoba.protobuf.ClimateProtos.IndoorClimate.Builder.class);
      }

      // Construct using com.vladzasoba.protobuf.ClimateProtos.IndoorClimate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTemperatureFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (temperatureBuilder_ == null) {
          temperature_ = null;
        } else {
          temperatureBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.vladzasoba.protobuf.ClimateProtos.internal_static_protobuf_IndoorClimate_descriptor;
      }

      @java.lang.Override
      public com.vladzasoba.protobuf.ClimateProtos.IndoorClimate getDefaultInstanceForType() {
        return com.vladzasoba.protobuf.ClimateProtos.IndoorClimate.getDefaultInstance();
      }

      @java.lang.Override
      public com.vladzasoba.protobuf.ClimateProtos.IndoorClimate build() {
        com.vladzasoba.protobuf.ClimateProtos.IndoorClimate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.vladzasoba.protobuf.ClimateProtos.IndoorClimate buildPartial() {
        com.vladzasoba.protobuf.ClimateProtos.IndoorClimate result = new com.vladzasoba.protobuf.ClimateProtos.IndoorClimate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (temperatureBuilder_ == null) {
            result.temperature_ = temperature_;
          } else {
            result.temperature_ = temperatureBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.vladzasoba.protobuf.ClimateProtos.IndoorClimate) {
          return mergeFrom((com.vladzasoba.protobuf.ClimateProtos.IndoorClimate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.vladzasoba.protobuf.ClimateProtos.IndoorClimate other) {
        if (other == com.vladzasoba.protobuf.ClimateProtos.IndoorClimate.getDefaultInstance()) return this;
        if (other.hasTemperature()) {
          mergeTemperature(other.getTemperature());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasTemperature()) {
          return false;
        }
        if (!getTemperature().isInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.vladzasoba.protobuf.ClimateProtos.IndoorClimate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.vladzasoba.protobuf.ClimateProtos.IndoorClimate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.vladzasoba.protobuf.ClimateProtos.ValueType temperature_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.vladzasoba.protobuf.ClimateProtos.ValueType, com.vladzasoba.protobuf.ClimateProtos.ValueType.Builder, com.vladzasoba.protobuf.ClimateProtos.ValueTypeOrBuilder> temperatureBuilder_;
      /**
       * <code>required .protobuf.ValueType temperature = 1;</code>
       */
      public boolean hasTemperature() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .protobuf.ValueType temperature = 1;</code>
       */
      public com.vladzasoba.protobuf.ClimateProtos.ValueType getTemperature() {
        if (temperatureBuilder_ == null) {
          return temperature_ == null ? com.vladzasoba.protobuf.ClimateProtos.ValueType.getDefaultInstance() : temperature_;
        } else {
          return temperatureBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protobuf.ValueType temperature = 1;</code>
       */
      public Builder setTemperature(com.vladzasoba.protobuf.ClimateProtos.ValueType value) {
        if (temperatureBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          temperature_ = value;
          onChanged();
        } else {
          temperatureBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protobuf.ValueType temperature = 1;</code>
       */
      public Builder setTemperature(
          com.vladzasoba.protobuf.ClimateProtos.ValueType.Builder builderForValue) {
        if (temperatureBuilder_ == null) {
          temperature_ = builderForValue.build();
          onChanged();
        } else {
          temperatureBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protobuf.ValueType temperature = 1;</code>
       */
      public Builder mergeTemperature(com.vladzasoba.protobuf.ClimateProtos.ValueType value) {
        if (temperatureBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              temperature_ != null &&
              temperature_ != com.vladzasoba.protobuf.ClimateProtos.ValueType.getDefaultInstance()) {
            temperature_ =
              com.vladzasoba.protobuf.ClimateProtos.ValueType.newBuilder(temperature_).mergeFrom(value).buildPartial();
          } else {
            temperature_ = value;
          }
          onChanged();
        } else {
          temperatureBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protobuf.ValueType temperature = 1;</code>
       */
      public Builder clearTemperature() {
        if (temperatureBuilder_ == null) {
          temperature_ = null;
          onChanged();
        } else {
          temperatureBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .protobuf.ValueType temperature = 1;</code>
       */
      public com.vladzasoba.protobuf.ClimateProtos.ValueType.Builder getTemperatureBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getTemperatureFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protobuf.ValueType temperature = 1;</code>
       */
      public com.vladzasoba.protobuf.ClimateProtos.ValueTypeOrBuilder getTemperatureOrBuilder() {
        if (temperatureBuilder_ != null) {
          return temperatureBuilder_.getMessageOrBuilder();
        } else {
          return temperature_ == null ?
              com.vladzasoba.protobuf.ClimateProtos.ValueType.getDefaultInstance() : temperature_;
        }
      }
      /**
       * <code>required .protobuf.ValueType temperature = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.vladzasoba.protobuf.ClimateProtos.ValueType, com.vladzasoba.protobuf.ClimateProtos.ValueType.Builder, com.vladzasoba.protobuf.ClimateProtos.ValueTypeOrBuilder> 
          getTemperatureFieldBuilder() {
        if (temperatureBuilder_ == null) {
          temperatureBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.vladzasoba.protobuf.ClimateProtos.ValueType, com.vladzasoba.protobuf.ClimateProtos.ValueType.Builder, com.vladzasoba.protobuf.ClimateProtos.ValueTypeOrBuilder>(
                  getTemperature(),
                  getParentForChildren(),
                  isClean());
          temperature_ = null;
        }
        return temperatureBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.IndoorClimate)
    }

    // @@protoc_insertion_point(class_scope:protobuf.IndoorClimate)
    private static final com.vladzasoba.protobuf.ClimateProtos.IndoorClimate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.vladzasoba.protobuf.ClimateProtos.IndoorClimate();
    }

    public static com.vladzasoba.protobuf.ClimateProtos.IndoorClimate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<IndoorClimate>
        PARSER = new com.google.protobuf.AbstractParser<IndoorClimate>() {
      @java.lang.Override
      public IndoorClimate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IndoorClimate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IndoorClimate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IndoorClimate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.vladzasoba.protobuf.ClimateProtos.IndoorClimate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_ValueType_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_ValueType_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_IndoorClimate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_IndoorClimate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0src/main/resources/messages/indoor_cli" +
      "mate.proto\022\010protobuf\"(\n\tValueType\022\014\n\004uni" +
      "t\030\001 \002(\t\022\r\n\005value\030\002 \002(\006\"9\n\rIndoorClimate\022" +
      "(\n\013temperature\030\001 \002(\0132\023.protobuf.ValueTyp" +
      "eB(\n\027com.vladzasoba.protobufB\rClimatePro" +
      "tos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_ValueType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_ValueType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_ValueType_descriptor,
        new java.lang.String[] { "Unit", "Value", });
    internal_static_protobuf_IndoorClimate_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_IndoorClimate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_IndoorClimate_descriptor,
        new java.lang.String[] { "Temperature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
